name: Helm Deploy Action
description: Deploys a helm chart
inputs:
  release:
    description: Helm release name. Will be combined with track if set.
  chart:
    description: Helm chart name.
  namespace:
    description: Kubernetes namespace name.
  values:
    description: Helm chart values, expected to be a YAML or JSON string.
  value-file:
    description: Additional value file to apply to the helm chart.
  repo:
    description: Custom helm repository.
  username:
    description: Custom helm repository username.
  password:
    description: Custom helm repository password.
runs:
  using: docker
  image: Dockerfile
